### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by syaoyou** [yayugu/twitter-great-rss#1]
ローカルで動かしてみたいのですが、セットアップ方法の概略をご指導いただけませんか？

**Comment by yayugu** [comment]
ふつうのRailsのセットアップをググってやってください
あとTwitterのConsumer Key/Secretを環境変数で渡せば動きます

https://github.com/yayugu/twitter-great-rss/blob/8e7edd62b258d6be0d6056a2343efb618a758468/lib/oauth_twitter.rb
